openapi: 3.0.1
info:
  title: CartonCapsAPI
  description: API for managing accounts and invitations
  version: '1.0'
  contact:
    name: Sean Woodward
    email: seanwoodward@seanwoodwardweb.com
    url: https://seanwoodwardweb.com
paths:
  /accounts:
    post:
      tags:
        - Accounts
      summary: Create a new account
      description: Create a new account. Provide only an email address. Their ID and Referral Code will be returned.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccount'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateAccount'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateAccount'
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Account'
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
            text/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Bad Request
    get:
      tags:
        - Accounts
      summary: Get a list of accounts
      description: Get a list of accounts. Neither Email Address nor Referral Code are required. With both empty, all accounts are returned.
      parameters:
        - name: EmailAddress
          in: query
          schema:
            type: string
        - name: ReferralCode
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
  /accounts/{accountID}:
    get:
      tags:
        - Accounts
      summary: Get an account by ID
      description: Get an account by ID
      parameters:
        - name: accountID
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Account'
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
            text/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Not Found
    delete:
      tags:
        - Accounts
      summary: Delete an account by ID
      description: Delete an account by ID
      parameters:
        - name: accountID
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
  /invitations:
    post:
      tags:
        - Invitations
      summary: Create a new invitation
      description: Create a new invitation. Provide the sender's Account ID and Referral Code, and the invited person's first name, last name, and email address. The invitation will be returned.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvitation'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateInvitation'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateInvitation'
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Invitation'
            application/json:
              schema:
                $ref: '#/components/schemas/Invitation'
            text/json:
              schema:
                $ref: '#/components/schemas/Invitation'
        '400':
          description: Bad Request
    get:
      tags:
        - Invitations
      summary: Get a list of invitations
      description: Get a list of invitations. Neither Account ID, Email Address, nor Referral Code are required. With all empty, all invitations are returned. Use this to check status of Invitations.
      parameters:
        - name: AccountID
          in: query
          schema:
            type: integer
            format: int32
        - name: EmailAddress
          in: query
          schema:
            type: string
        - name: ReferralCode
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invitation'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invitation'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invitation'
        '404':
          description: Not Found
  /invitations/{invitationID}:
    get:
      tags:
        - Invitations
      summary: Get an invitation by ID
      description: Get an invitation by ID
      parameters:
        - name: invitationID
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Invitation'
            application/json:
              schema:
                $ref: '#/components/schemas/Invitation'
            text/json:
              schema:
                $ref: '#/components/schemas/Invitation'
        '404':
          description: Not Found
    delete:
      tags:
        - Invitations
      summary: Delete an invitation by ID
      description: Delete an invitation by ID
      parameters:
        - name: invitationID
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
  /invitations/{invitationID}/accept:
    post:
      tags:
        - Invitations
      summary: Accept an invitation
      description: Accept an invitation. Provide the accepted Account ID. The invitation will be updated with the accepted Account ID and accepted date.
      parameters:
        - name: invitationID
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: acceptedAccountID
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Invitation'
            application/json:
              schema:
                $ref: '#/components/schemas/Invitation'
            text/json:
              schema:
                $ref: '#/components/schemas/Invitation'
        '404':
          description: Not Found
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int32
        email:
          type: string
          nullable: true
        referralCode:
          type: string
          nullable: true
      additionalProperties: false      
    CreateAccount:
      type: object
      properties:
        emailAddress:
          type: string
          nullable: true
      additionalProperties: false
    CreateInvitation:
      type: object
      properties:
        senderAccountID:
          type: integer
          format: int32
        senderReferralCode:
          type: string
          nullable: true
        invitedFirstName:
          type: string
          nullable: true
        invitedLastName:
          type: string
          nullable: true
        invitedEmail:
          type: string
          nullable: true
      additionalProperties: false
    Invitation:
      type: object
      properties:
        id:
          type: integer
          format: int32
        senderAccountID:
          type: integer
          format: int32
        senderReferralCode:
          type: string
          nullable: true
        invitedAt:
          type: string
          format: date-time
          nullable: true
        invitedFirstName:
          type: string
          nullable: true
        invitedLastName:
          type: string
          nullable: true
        invitedEmail:
          type: string
          nullable: true
        acceptedAt:
          type: string
          format: date-time
          nullable: true
        acceptedAccountID:
          type: integer
          format: int32
          nullable: true
        referralURL:
          type: string
          nullable: true
      additionalProperties: false
