// <auto-generated />
using System;
using CartonCapsDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartonCapsDbContext.Migrations
{
    [DbContext(typeof(CartonCapsEFDbContext))]
    partial class CartonCapsEFDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartonCapsDbContext.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CartonCapsDbContext.Models.Invitation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AcceptedAccountID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InvitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvitedFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvitedLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderAccountID")
                        .HasColumnType("int");

                    b.Property<string>("SenderReferralCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AcceptedAccountID");

                    b.HasIndex("SenderAccountID");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("CartonCapsDbContext.Models.Invitation", b =>
                {
                    b.HasOne("CartonCapsDbContext.Models.Account", "AcceptedAccount")
                        .WithMany("InvitationsAccepted")
                        .HasForeignKey("AcceptedAccountID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CartonCapsDbContext.Models.Account", "SourceAccount")
                        .WithMany("InvitationsSent")
                        .HasForeignKey("SenderAccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedAccount");

                    b.Navigation("SourceAccount");
                });

            modelBuilder.Entity("CartonCapsDbContext.Models.Account", b =>
                {
                    b.Navigation("InvitationsAccepted");

                    b.Navigation("InvitationsSent");
                });
#pragma warning restore 612, 618
        }
    }
}
